export function productoVacio () {
  return {
    code: 'xxxxxxxxxxxxxxxx',
    complete: 0,
    generic_name: '####### ###',
    ingredients_analysis_tags: [
      'en:palm-oil-content-unknown',
      'en:vegan-status-unknown',
      'en:vegetarian-status-unknown'],
    labels_tags: [],
    origins: '### ####### #',
    manufacturing_places: '####### ###, #######',
    product_name: '##### ########### ####### ## ###### ##',
    nutriments: {
      calcium: 0.0,
      calcium_100g: 0.0,
      calcium_serving: 0.0,
      calcium_unit: 'mg',
      calcium_value: 0,
      'carbon-footprint-from-known-ingredients_100g': 0.0,
      carbohydrates: 0.0,
      carbohydrates_100g: 0.0,
      carbohydrates_serving: 0,
      carbohydrates_unit: 'g',
      carbohydrates_value: 0.0,
      cholesterol: 0,
      cholesterol_100g: 0,
      cholesterol_serving: 0,
      cholesterol_unit: 'mg',
      cholesterol_value: 0,
      energy: 0,
      'energy-kcal': 0,
      'energy-kcal_100g': 0,
      'energy-kcal_serving': 0,
      'energy-kcal_unit': 'kcal',
      'energy-kcal_value': 0,
      energy_100g: 0,
      energy_serving: 0,
      energy_unit: 'kcal',
      energy_value: 0,
      fat: 0.0,
      fat_100g: 0.0,
      fat_serving: 0,
      fat_unit: 'g',
      fat_value: 0.0,
      fiber: 0.0,
      fiber_100g: 0.0,
      fiber_serving: 0.0,
      fiber_unit: 'g',
      fiber_value: 0.0,
      'fruits-vegetables-nuts-estimate-from-ingredients_100g': 0,
      iron: 0.00069,
      iron_100g: 0.0,
      iron_serving: 0.0,
      iron_unit: 'mg',
      iron_value: 0.0,
      'nova-group': 0,
      'nova-group_100g': 0,
      'nova-group_serving': 0,
      'nutrition-score-fr': 0,
      'nutrition-score-fr_100g': 0,
      proteins: 0.0,
      proteins_100g: 0.0,
      proteins_serving: 0,
      proteins_unit: 'g',
      proteins_value: 0.0,
      salt: 0.0,
      salt_100g: 0.0,
      salt_serving: 0.0,
      salt_unit: 'mg',
      salt_value: 0,
      'saturated-fat': 0.0,
      'saturated-fat_100g': 0.0,
      'saturated-fat_serving': 0.0,
      'saturated-fat_unit': 'g',
      'saturated-fat_value': 0.0,
      sodium: 0.0,
      sodium_100g: 0.0,
      sodium_serving: 0.0,
      sodium_unit: 'mg',
      sodium_value: 0,
      sugars: 0.0,
      sugars_100g: 0.0,
      sugars_serving: 0,
      sugars_unit: 'g',
      sugars_value: 0.0,
      'trans-fat': 0,
      'trans-fat_100g': 0,
      'trans-fat_serving': 0,
      'trans-fat_unit': 'g',
      'trans-fat_value': 0,
      'vitamin-a': 0.000,
      'vitamin-a_100g': 0.000,
      'vitamin-a_serving': 0.00e-05,
      'vitamin-a_unit': 'IU',
      'vitamin-a_value': 0,
      'vitamin-c': 0,
      'vitamin-c_100g': 0,
      'vitamin-c_serving': 0,
      'vitamin-c_unit': 'mg',
      'vitamin-c_value': 0
    },
    ingredients: [
      {
        id: 'XXXXXX XXXX',
        percent_max: 100,
        percent_min: '0',
        rank: 1,
        text: 'xxxx xxxx xxx xxxx',
        vegan: 'yes',
        vegetarian: 'yes'
      }
    ],
    allergens_tags: [
    ],
    additives_tags: [
    ],
    packaging_tags: [
      '**** ******',
      '##########'
    ],
    quantity: '0 g',
    sustainability: {
      sustainability_level: 3
    }
  }
}
