export function productoVacio () {
  return {
    code: 'xxxxxxxxxxxxxxxx',
    complete: 1,
    generic_name: '####### ###',
    ingredients_analysis_tags: [
      'en:palm-oil-content-unknown',
      'en:non-vegan',
      'en:vegetarian'],
    labels_tags: ['en:gluten-free'],
    origins: '### ####### #',
    manufacturing_places: '####### ###, #######',
    product_name: '##### ########### ####### ## ###### ##',
    nutriments: {
      calcium: 0.038,
      calcium_100g: 0.038,
      calcium_serving: 0.0198,
      calcium_unit: 'mg',
      calcium_value: 38,
      carbohydrates: 71.15,
      carbohydrates_100g: 71.15,
      carbohydrates_serving: 37,
      carbohydrates_unit: 'g',
      carbohydrates_value: 71.15,
      cholesterol: 0,
      cholesterol_100g: 0,
      cholesterol_serving: 0,
      cholesterol_unit: 'mg',
      cholesterol_value: 0,
      energy: 1611,
      'energy-kcal': 1611,
      'energy-kcal_100g': 1611,
      'energy-kcal_serving': 838,
      'energy-kcal_unit': 'kcal',
      'energy-kcal_value': 385,
      energy_100g: 1611,
      energy_serving: 838,
      energy_unit: 'kcal',
      energy_value: 385,
      fat: 7.69,
      fat_100g: 7.69,
      fat_serving: 4,
      fat_unit: 'g',
      fat_value: 7.69,
      fiber: 1.9,
      fiber_100g: 1.9,
      fiber_serving: 0.988,
      fiber_unit: 'g',
      fiber_value: 1.9,
      'fruits-vegetables-nuts-estimate-from-ingredients_100g': 0,
      iron: 0.00069,
      iron_100g: 0.00069,
      iron_serving: 0.000359,
      iron_unit: 'mg',
      iron_value: 0.69,
      'nova-group': 4,
      'nova-group_100g': 4,
      'nova-group_serving': 4,
      'nutrition-score-fr': 4,
      'nutrition-score-fr_100g': 4,
      proteins: 9.62,
      proteins_100g: 9.62,
      proteins_serving: 5,
      proteins_unit: 'g',
      proteins_value: 9.62,
      salt: 0.72,
      salt_100g: 0.72,
      salt_serving: 0.374,
      salt_unit: 'mg',
      salt_value: 720,
      'saturated-fat': 1.92,
      'saturated-fat_100g': 1.92,
      'saturated-fat_serving': 0.998,
      'saturated-fat_unit': 'g',
      'saturated-fat_value': 1.92,
      sodium: 0.288,
      sodium_100g: 0.288,
      sodium_serving: 0.15,
      sodium_unit: 'mg',
      sodium_value: 288,
      sugars: 13.46,
      sugars_100g: 13.46,
      sugars_serving: 7,
      sugars_unit: 'g',
      sugars_value: 13.46,
      'trans-fat': 0,
      'trans-fat_100g': 0,
      'trans-fat_serving': 0,
      'trans-fat_unit': 'g',
      'trans-fat_value': 0,
      'vitamin-a': 0.0001155,
      'vitamin-a_100g': 0.0001155,
      'vitamin-a_serving': 6.01e-05,
      'vitamin-a_unit': 'IU',
      'vitamin-a_value': 385,
      'vitamin-c': 0,
      'vitamin-c_100g': 0,
      'vitamin-c_serving': 0,
      'vitamin-c_unit': 'mg',
      'vitamin-c_value': 0
    },
    sustainability: {
      sustainability_level: 2.5
    }
  }
}
